binary_build_commands: go build -o /bin/prune .
build_root:
  from_repository: true
images:
- dockerfile_literal: FROM bin
  from: bin
  to: shiftstack-prune-image
- dockerfile_literal: |-
    FROM src
    RUN ./hack/dnf_safe -y install python3-openstackclient python3-octaviaclient jq && dnf clean all
    ADD openshift-install /usr/bin/openshift-install
    RUN python -m pip install yq
  from: src
  inputs:
    installer:
      paths:
      - destination_dir: .
        source_path: /bin/openshift-install
  to: openstack-installer
resources:
  '*':
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: go-fmt
  commands: if [ "$(gofmt -s -l . | tee /dev/stderr | wc -l)" -gt 0 ]; then exit 1;
    fi
  container:
    from: src
- as: go-vet
  commands: go vet ./...
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: shiftstack
  repo: prune
