binary_build_commands: |-
  go build -o /bin/doctext ./cmd/doctext
  go build -o /bin/pretriage ./cmd/pretriage
  go build -o /bin/triage ./cmd/triage
  go build -o /bin/posttriage ./cmd/posttriage
build_root:
  from_repository: true
promotion:
  to:
  - additional_images:
      bugwatcher: bin
    name: tooling
    namespace: shiftstack
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: go-vet
  commands: go vet ./...
  container:
    from: src
- as: go-fmt
  commands: '! gofmt -l -s $(find . -path ''./.git'' -o -path ''./vendor'' -prune
    -o -type f -name ''*.go'' -print) | grep .'
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: shiftstack
  repo: bugwatcher
